config/routes.rb
Dinheiro::Application.routes.draw do

  devise_for :users

  root 'info#index'

  resources :accounts

  resources :categories

  resources :rules

  resources :transactions

  resources :stats do
    collection do
      get 'categories/:category_id', to: 'stats#category', as: :category
    end
  end

  

end

app/models/rule.rb
class Rule < ActiveRecord::Base
  FIELDS = {
    date: 'Date',
    payee: 'Payee',
    type: 'Type'
  }
  OPERATORS = {
    contains: 'Contains',
    endswith: 'Ends With',
    startswith: 'Starts With'
  }

  belongs_to :category

  validates_presence_of :content
  validates_inclusion_of :field, in: FIELDS.keys.map { |f| f.to_s }, allow_nil: false
  validates_inclusion_of :operator, in: OPERATORS.keys.map { |o| o.to_s }, allow_nil: false

  before_save :normalize!
  after_save :execute


  def normalize!
    self.content = content.downcase
  end

  def execute
    return unless FIELDS.keys.include? field.to_sym
    # TODO: This seems bad
    filter = case operator
               when 'contains'
                 "%#{content}%"
               when 'endswith'
                 "%#{content}"
               when 'startswith'
                 "#{content}%"
             end
    matches = Transaction.where("#{field} LIKE :content", content: filter)
    matches.update_all(category_id: category_id)
  end

end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  before_action :set_rule, only: [:show, :edit, :update, :destroy]

  # GET /rules
  # GET /rules.json
  def index
    @rules = Rule.all
  end

  # GET /rules/1
  # GET /rules/1.json
  def show
  end

  # GET /rules/new
  def new
    # Allow category_id to be specified as an optional param
    # Default field to payee
    @rule = Rule.new(params.permit(:category_id).merge({ field: 'payee' }))
  end

  # GET /rules/1/edit
  def edit
  end

  # POST /rules
  # POST /rules.json
  def create
    @rule = Rule.new(rule_params)

    respond_to do |format|
      if @rule.save
        format.html { redirect_to edit_category_path(id: @rule.category_id), notice: 'Rule was successfully created.' }
        format.json { render action: 'show', status: :created, location: @rule }
      else
        format.html { render action: 'new' }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rules/1
  # PATCH/PUT /rules/1.json
  def update
    respond_to do |format|
      if @rule.update(rule_params)
        format.html { redirect_to edit_category_path(id: @rule.category_id), notice: 'Rule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rules/1
  # DELETE /rules/1.json
  def destroy
    @rule.destroy
    respond_to do |format|
      format.html { redirect_to edit_category_path(id: @rule.category_id) }
      format.json { head :no_content }
    end
  end

  private
    def set_rule
      @rule = Rule.find(params[:id])
    end

    # Never trusst parameters from the scary internet, only allow the white list through.
    def rule_params
      params.require(:rule).permit(:category_id, :field, :operator, :content)
    end
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/rules/_form.html.erb
<div class="span12">
  <%= form_for(@rule) do |f| %>
    <% if @rule.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@rule.errors.count, 'error') %> prohibited this rule from being saved:</h2>

        <ul>
          <% @rule.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= label_tag :category %>
      <%= text_field_tag :category, @rule.category.name, class: 'form-control', readonly: true %>
      <%= f.hidden_field :category_id %>
    </div>
    <div class="form-group">
      <%= f.label :field %>
      <%= f.select :field, Rule::FIELDS.map { |id,name| [name, id] }, {}, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :operator %>
      <%= f.select :operator, Rule::OPERATORS.map { |id,name| [name, id] }, {}, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :content %>
      <%= f.text_field :content, class: 'form-control' %>
    </div>

    <div class="actions">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/rules/edit.html.erb
<h1>Editing rule</h1>

<%= render 'form' %>

<%= link_to 'Show', @rule %> |
<%= link_to 'Back', rules_path %>

app/views/rules/index.html.erb
<h1>Listing rules</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @rules.each do |rule| %>
      <tr>
        <td><%= link_to 'Show', rule %></td>
        <td><%= link_to 'Edit', edit_rule_path(rule) %></td>
        <td><%= link_to 'Destroy', rule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rule', new_rule_path %>

app/views/rules/new.html.erb
<h1>New rule</h1>

<%= render 'form' %>

<%= link_to 'Back', rules_path %>

app/views/rules/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_rule_path(@rule) %> |
<%= link_to 'Back', rules_path %>