config/routes.rb
Dinheiro::Application.routes.draw do

  devise_for :users

  root 'info#index'

  resources :accounts

  resources :categories

  resources :rules

  resources :transactions

  resources :stats do
    collection do
      get 'categories/:category_id', to: 'stats#category', as: :category
    end
  end

  

end

app/views/layouts/_messages.html.erb
<% if flash[:alert].present? %>
  <div class="alert alert-info">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, flash[:alert], :id => "flash_alert" %>
  </div>
<% end %>
<% if flash[:notice].present? %>
  <div class="alert alert-success">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, flash[:notice], :id => "flash_notice" %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar-header">
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <%= link_to 'Dinheiro', root_path, class: 'navbar-brand' %>
</div>
<div class="collapse navbar-collapse">
  <ul class="nav navbar-nav">
    <li id="home-tab"><%= link_to 'Home', root_path %></li>
    <li id="accounts-tab"><%= link_to 'Accounts', accounts_path %></li>
    <li id="categories-tab"><%= link_to 'Categories', categories_path %></li>
    <li id="transactions-tab"><%= link_to 'Transactions', transactions_path %></li>
    <li id="stats-tab"><%= link_to 'Stats', stats_path %></li>
  </ul>
  <ul class="nav navbar-nav pull-right">
    <% if user_signed_in? %>
      <li>
        <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
      </li>
    <% else %>
      <li>
        <%= link_to('Login', new_user_session_path)  %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>

  <title>Dinheiro</title>

  <style>
      /* Ensure the body starts below the top navbar
       * (See "Fixed to top" on http://twitter.github.io/bootstrap/components.html#navbar */
    body {
      padding-top: 70px;
    }
  </style>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'bootstrap.min' %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'bootstrap.min', 'highcarts/highcharts' %>

</head>
<body>
  <header class="navbar navbar-inverse navbar-fixed-top">
    <nav class="navbar-inner">
      <div class="container">
        <%= render 'layouts/navigation' %>
      </div>
    </nav>
  </header>
  <main role="main">
    <div class="container">
      <div class="content">
        <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div>
    </div>
  </main>

</body>
</html>